### ISSUE TITLE
Hello Sir I need This project 

### ISSUE THREAD

**Issue by ersurajkumar1999** [ceosano/MenuMacros#1]
It works when I run dev but when I try to run 'next build' it throws errors. Looking for someone with experience with nextjs that can solve the problem.

I am fixing this issues

**Comment by doyen118** [comment]
I fixed it. Please send me a message if you need the help.

**Comment by doyen118** [comment]
I attached the screenshot for the success of building.
![Uploading Screenshot_3.png…]()

**Comment by doyen118** [comment]
Please check this screenshot of build success.

![Screenshot_3](https://github.com/SandraPapo/MenuMacros/assets/164857640/94e94c34-d729-438a-b4a8-d735762fd879)

**Comment by katongole-isaac** [comment]
Greetings sir, I think the project builds successfully. 

You can take a look at the output of the build. 
![the_fix](https://github.com/SandraPapo/MenuMacros/assets/87535414/22be5e66-6e78-47d4-a93d-f88739479d95)

**Comment by ersurajkumar1999** [comment]
Hello Sir
![image](https://github.com/SandraPapo/MenuMacros/assets/146355358/42fd41e3-8b46-488e-97da-5fc30d886c91)

here your live site
https://menumacros-app.netlify.app/


If any issue pls connect on mail

Thanks
Er Suraj Kumar
er.surajkumar1999@gmail.com

**Comment by ersurajkumar1999** [comment]
here your live site
https://menumacros-app.netlify.app/

![image](https://github.com/SandraPapo/MenuMacros/assets/146355358/65de363f-4b44-4f37-9ea5-cab022c217f3)

If any issue pls connect on mail

Thanks
Er Suraj Kumar
er.surajkumar1999@gmail.com

**Comment by ersurajkumar1999** [comment]
Hello Sir,
How ar doing ?
Could you please provide a thorough explanation of this issue? I would like to understand it properly before proceeding to address it.

Thank you,
Suraj Kumar
er.surajkumar1999@gmail.com
